export const ADD_TO_CART="ADD_TO_CART";
export const REMOVE_FROM_CART="REMOVE_FROM_CART";
export const EMTY_CART="EMPTY_CART";
export const PRODUCT_ACTION="PRODUCT_ACTION";
export const SET_PRODUCT_LIST="SET_PRODUCT_LIST";
export const SEARCH_PRODUCT="SEARCH_PRODUCT";